<?php
add_action('admin_menu', 'scm_saas_admin_menu');

function scm_saas_admin_menu() {
    add_menu_page(
        'SCM SaaS Dashboard',
        'SCM SaaS',
        'manage_options',
        'scm-saas-dashboard',
        'scm_saas_render_dashboard',
        'dashicons-chart-line',
        3
    );

    add_submenu_page('scm-saas-dashboard', 'Forecasting', 'Forecasting', 'manage_options', 'scm-saas-forecasting', 'scm_saas_render_forecast');

    add_submenu_page('scm-saas-dashboard', 'Inventory Optimization', 'Inventory', 'manage_options', 'scm-saas-inventory', 'scm_saas_render_inventory');

    add_submenu_page('scm-saas-dashboard', 'DB Inspector', 'DB Inspector', 'manage_options', 'scm-db-inspector', 'scm_saas_render_db_inspector', 'dashicons-database', 75);

    add_submenu_page('scm-saas-dashboard', 'AI Forecast', 'AI Forecast', 'manage_options', 'scm-ai-forecast', 'scm_saas_render_ai_forecast', 'dashicons-chart-line', 76);
}


/**
 * Render the main SCM SaaS Dashboard page
 */
function scm_saas_render_dashboard() {
    echo '<div class="wrap">';
    echo '<h1>SCM SaaS Dashboard</h1>';
    echo '<p>Welcome to the Supply Chain Management Suite. Use the menu to access modules like Demand Forecasting, Inventory Optimization, Supplier Performance, and KPI Analytics.</p>';
    echo '</div>';
}

/**
 * Render the Demand Forecasting page
 */
function scm_saas_render_forecast() {
    echo '<div class="wrap">';
    echo '<h1>Demand Forecasting</h1>';
    echo '<p>Upload sales data and view forecasts generated by AI models or moving average techniques.</p>';
    // You can include your form and canvas elements here or include separate PHP partials
    echo '</div>';
}

/**
 * Render the Inventory Optimization page
 */
function scm_saas_render_inventory() {
    echo '<div class="wrap">';
    echo '<h1>Inventory Optimization</h1>';
    echo '<p>Calculate economic order quantities, safety stock, reorder points, and more.</p>';
    // Add inventory input forms and display areas here or load partials
    echo '</div>';
}

function scm_saas_render_db_inspector() {
    $tables = SCM_DB_Inspector::list_tables();
    echo '<h2>SCM Tables</h2><ul>';
    foreach ($tables as $table) {
        echo '<li>' . esc_html($table[0]) . '</li>';
    }
    echo '</ul>';
}

function scm_saas_render_ai_forecast() {
    if (!current_user_can('manage_options')) {
        wp_die('Unauthorized');
    }
    require_once plugin_dir_path(__FILE__) . 'admin/run-ai-forecast.php';
}
